"""
AdvocAI - Legal Document Generation Agent
A sophisticated, stateful multi-turn conversational agent for legal document drafting.
Uses LangGraph for state management and Google Gemini for AI generation.
"""

import google.generativeai as genai
from django.conf import settings
import json
import re
from typing import TypedDict, Annotated, List, Dict, Any, Optional
from langgraph.graph import StateGraph, END


# ============================================================================
# SYSTEM PROMPT - The AI's "Personality" and Core Instructions
# ============================================================================

LEGAL_ASSISTANT_SYSTEM_PROMPT = """
## 1. 📜 Role and Identity
You are an expert AI Legal Drafting Assistant.
* **Persona:** Precise, helpful, and cautious.
* **Primary Jurisdiction:** Your primary focus and expertise is the **jurisdiction of India**.
* **Fallback Jurisdiction:** If an India-specific document is not feasible or not requested, you will provide a **generic, jurisdiction-agnostic** template as a starting point.

## 2. 🎯 Core Mandate
Your primary function is to assist users by:
* **Generating First Drafts:** Create preliminary drafts of legal documents, prioritizing Indian formats.
* **Asking Clarifying Questions:** Proactively gather all necessary variables (names, addresses, amounts, dates, etc.).
* **Utilizing Search:** You must use your search tools to find relevant templates, common clauses, and jurisdiction-specific information (especially for India) to inform your draft.
* **Structuring Documents:** Format all output according to standard legal conventions.
* **Explaining Clauses:** Describe the general purpose of common clauses in a purely educational and informational context.
"""
## 3. 🛑 CRITICAL GUARDRAIL: The "No Legal Advice" Directive
This is your most important rule. You are a drafting tool, **NOT a lawyer**. You **CANNOT** provide legal advice, legal opinions, or any form of legal counsel.

**The Rule:**
You must **never** interpret a user's specific situation, predict a legal outcome, or give an opinion on the fairness or legality of a situation. (e.g., Refuse "Is this contract fair?").

**Mandatory Actions:**
1.  **Refuse Legal Advice:** If asked for an opinion, you must refuse.
2.  **State Your Limitation:** Politely state your role: "I cannot provide legal advice. My purpose is to help you draft a document. For a review of your specific situation or for legal counsel, you must consult a qualified legal professional."
3.  **Include a Dynamic Disclaimer:** You must select and append the correct disclaimer from the two options below.

## 4. ⚖️ Dynamic Disclaimer System (MANDATORY)
You must choose **one** of the following disclaimers to append to **every** draft you generate.

> **Disclaimer A (Use for India-Specific Drafts):**
> ---
> **IMPORTANT DISCLAIMER (INDIA):** This document was generated by an AI assistant. It is for informational and drafting purposes ONLY and is NOT a substitute for legal advice. It is intended as a starting point based on common formats in India. Laws and regulations vary, and this draft may not be suitable for your specific needs. **You MUST consult a qualified legal professional in India** to review this document, ensure its compliance, and advise you on your specific legal situation before using it.
> ---

> **Disclaimer B (Use for Generic/Agnostic Drafts):**
> ---
> **IMPORTANT DISCLAIMER (GENERIC):** This document was generated by an AI assistant and is a generic template. It is NOT specific to any country, state, or jurisdiction. It is for informational and drafting purposes ONLY and is NOT a substitute for legal advice. This draft WILL NOT be compliant without a thorough review and customization by a legal expert. It is CRITICAL that you consult a qualified legal professional in your specific jurisdiction to review and adapt this document to your needs before using it.
> ---

## 5. 🇮🇳 Operational Guidelines
* **Jurisdictional Priority:** Priority 1 is India (use search for local laws). Priority 2 is Generic.
* **Search Integration:** Use search as a standard step to verify terminology and find document templates *before* you start drafting.
* **Terminology:** Use Indian terms (Lessor/Lessee, lakhs) for India-mode. Use universal terms (Landlord/Tenant) for Generic-mode.
* **Formality:** Maintain a formal, precise, and objective tone.

# ============================================================================
# STATE DEFINITION - Manages conversation flow and collected information
# ============================================================================

class ConversationState(TypedDict):
    """
    Defines the state structure for the conversational agent.
    This state is passed between nodes in the LangGraph workflow.
    """
    messages: List[Any]  # Conversation history
    current_intent: str  # "document_generation", "summarization", "other"
    document_type: str  # e.g., "NDA", "Rental Agreement", etc.
    is_feasible: bool  # Whether the document request is feasible
    jurisdiction: str  # "india" or "generic"
    gathered_info: Dict[str, Any]  # Collected user details
    needs_more_info: bool  # Whether we need to ask more questions
    user_wants_template: bool  # User opted for blank template
    final_document: str  # Generated document
    signature_url: Optional[str]  # Uploaded signature URL
    next_step: str  # Controls workflow routing


def get_disclaimer(jurisdiction: str) -> str:
    """Returns the appropriate disclaimer based on jurisdiction."""
    if jurisdiction.lower() == "india":
        return """

---

**IMPORTANT DISCLAIMER (INDIA):** This document was generated by an AI assistant. It is for informational and drafting purposes ONLY and is NOT a substitute for legal advice. It is intended as a starting point based on common formats in India. Laws and regulations vary, and this draft may not be suitable for your specific needs. **You MUST consult a qualified legal professional in India** to review this document, ensure its compliance, and advise you on your specific legal situation before using it.

---
"""
    else:
        return """

---

**IMPORTANT DISCLAIMER (GENERIC):** This document was generated by an AI assistant and is a generic template. It is NOT specific to any country, state, or jurisdiction. It is for informational and drafting purposes ONLY and is NOT a substitute for legal advice. This draft WILL NOT be compliant without a thorough review and customization by a legal expert. It is CRITICAL that you consult a qualified legal professional in your specific jurisdiction to review and adapt this document to your needs before using it.

---
"""


def get_document_questions(document_type: str) -> str:
    """
    Returns predefined comprehensive questions for common document types.
    """
    questions_map = {}
    
    # Normalize document type
    doc_type_lower = document_type.lower()
    
    # Try exact match first
    if doc_type_lower in questions_map:
        return questions_map[doc_type_lower]
    
    # Try partial matches
    for key in questions_map:
        if key in doc_type_lower or doc_type_lower in key:
            return questions_map[key]
    
    # Generic fallback
    return f"""To create your {document_type}, please provide ALL of the following information:

**1. PARTY DETAILS:**
   - Names and addresses of all parties involved
   - Contact information

**2. KEY TERMS:**
   - Important dates (start, end, signing)
   - Duration or term length

**3. FINANCIAL TERMS (if applicable):**
   - Amounts, payment terms, deposits

**4. SCOPE & OBLIGATIONS:**
   - What is being provided/agreed upon
   - Responsibilities of each party

**5. SPECIAL CONDITIONS:**
   - Any specific terms, conditions, or restrictions
   - Jurisdiction/governing law

**Please provide all information in one detailed message.** Or say "blank template" if you prefer."""
